name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        pytest --maxfail=5 --disable-warnings -q --html=pytest-report.html

    - name: Check code style with flake8
      run: |
        flake8 . --max-line-length=120 --format=html --output-file=flake8-report.html

    - name: Upload pytest result as HTML report
      uses: actions/upload-artifact@v2
      with:
        name: pytest-report
        path: pytest-report.html  # Вказуємо правильний шлях до звіту

    - name: Upload flake8 result as HTML report
      uses: actions/upload-artifact@v2
      with:
        name: flake8-report
        path: flake8-report.html  # Вказуємо правильний шлях до звіту
